#!/bin/bash
#PBS -l nodes=1:ppn=16:xk
#PBS -l walltime=01:00:00
#PBS -N cnn_validation
#PBS -e logs/log.${PBS_JOBNAME}_NN_${PBS_NUM_NODES}_${PBS_JOBID}.err
#PBS -o logs/log.${PBS_JOBNAME}_NN_${PBS_NUM_NODES}_${PBS_JOBID}.out
cd $PBS_O_WORKDIR
mkdir -p logs
module load bwpy
module load bwpy-mpi
source ~/.virtualenv/pytorch-spring2018/bin/activate
#export MPICH_RMA_OVER_DMAPP=1
#export MPICH_MAX_THREAD_SAFETY=multiple

#aprun -cc none -n 8 -d 16 -N 1 -b -- python \
#    simple_linear_regressin_distributed_train.py
LANG=C.UTF-8 
LC_ALL=C.UTF-8
#export LD_PRELOAD=/opt/cray/profiler/newest/libprofiler-shared.so

MODEL="inception_v3"
MBS=16
CHPT="~/scratch/pytorch_cpts/distributed_cnn_train_NN_8_8728297.bw/epoch_0_iter_80"

echo "Validating $MODEL"

echo "Mini Batch Size $MBS"

#aprun -cc none -n 1 -d 16 -N 1 -b -- python \
aprun -cc none -n $PBS_NUM_NODES -d 16 -N 1 -b -- python \
    cnn_validation.py \
    ~/scratch/ImageNet/class-dir-imagenet/validation/Images/ \
    --batch-size $MBS \
    --checkpoint $CHPT \
    --model $MODEL #\
#1> ${PBS_O_WORKDIR}/logs/apout.${PBS_JOBNAME}_NN_${PBS_NUM_NODES}_${PBS_JOBID}.out \
#2> ${PBS_O_WORKDIR}/logs/apout.${PBS_JOBNAME}_NN_${PBS_NUM_NODES}_${PBS_JOBID}.err
